admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/{_locale}
    requirements:
        _locale: 'en|hu'

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /
