parameters:
    author_manager.class: Blog\CoreBundle\Services\AuthorManager
    post_manager.class: Blog\CoreBundle\Services\PostManager
    tag_manager.class: Blog\CoreBundle\Services\TagManager

services:
    core.author_manager:
        class: '%author_manager.class%'
        arguments: ['@doctrine.orm.entity_manager']

    core.post_manager:
        class: '%post_manager.class%'
        arguments: ['@doctrine.orm.entity_manager', '@form.factory']

    core.tag_manager:
        class: '%tag_manager.class%'
        arguments: ['@doctrine.orm.entity_manager']
